name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  PG_HOST: localhost
  PG_PORT: 5432
  PG_USER: lucid
  PG_PASSWORD: secret
  PG_DB_NAME: lucid
  MATT_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
  PORT: 3333
  HOST: 0.0.0.0
  NODE_ENV: development
  APP_KEY: _9E_D2KJtq5sEn64BvznsPLAMKi2f6jZ
  DB_CONNECTION: pg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with: 
          node-version: "14.x"
        
      - name: Install packages
        run: npm install

      - name: Build Adonis application
        run: npm run build
      
      - name: Run migration
        run: node build/ace migration:run
        
      - name: Run seeder
        run: node build/ace db:seed
        
      - name: Run tests
        run: npm run test
  
      - name: Lint codebase
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: lucid
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: lucid
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
